version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: intersection_metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: intersection_metrics
      DATABASE_URL: postgresql://admin:admin123@db:5432/intersection_metrics
    entrypoint: ["/app/wait-for-postgres.sh", "db", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  generator:
    build: ./generator
    ports:
      - "5001:5001"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8000

volumes:
  db_data:
